spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/xz_match?useUnicode=true&characterEncoding=utf8&useSSL=false
    url: jdbc:mysql://localhost:8066/herocheer-uac?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    database: 3
    port: 6379
    password: chenwf
    timeout: 5000ms
dubbo:
  application:
    name: herocheer-uac-provider
  scan:
    base-packages: com.herocheer.uac.service
  protocol:
    id: dubbo
    name: dubbo
    port: 17004
  provider:
    timeout: 60000 #超时时间ms
    retries: 0     #远程服务调用重试次数, 不包括第一次调用, 不需要重试请设为0
    filter: -exception #服务提供方远程调用过程拦截器名称, 多个名称用逗号分隔
  consumer:
    timeout: 60000 #超时时间ms
    retries: 0     #远程服务调用重试次数, 不包括第一次调用, 不需要重试请设为0
    check: false  #是否检查
  service:
    loadbalance: roundrobin #负载均衡： 轮询
  registry:
    address: zookeeper://localhost:2181 #注册中心
#    address: nacos://localhost:8848 #注册中心
seata:
  application-id: ${dubbo.application.name}
  tx-service-group: seata_herocheer_tx_group
  service:
    vgroup-mapping:
      seata_herocheer_tx_group: default
#    grouplist:
#      default: localhost:8091
  registry:
    type: zk
    zk:
      server-addr: localhost:2181
      session-timeout: 10000
      connect-timeout: 20000
      cluster: default
    nacos:
      server-addr: localhost:8848
      cluster: default
      username: nacos
      password: nacos
      namespace: seata
  config:
    type: zk
    zk:
      server-addr: localhost:2181
      session-timeout: 10000
      connect-timeout: 20000
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      namespace: seata




