spring:
  redis:
    host: localhost
    database: 3
    port: 6379
    password: chenwf
    timeout: 5000ms
dubbo:
  application:
    name: herocheer-order-web
    id: herocheer-order-web
  consumer:
    timeout: 60000
    retries: 0
    check: false
  service:
      loadbalance: roundrobin
  registry:
      address: zookeeper://localhost:2181
swagger:
  title: order模块
  description: 订单模块
  version: 1.0.0
  termsOfServiceUrl: http://localhost:18081/
  license:
  licenseUrl:
  basePackage: com.herocheer.order.controller
  contact:
    name: chenwf
    url: http://localhost:18081/
    email: 349830964@qq.com


